Frontend/Controllers/ShippingInstructionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class ShippingInstructionController : Controller
    {
        private string moduleCode = "ShippingInstructionMng";

        // GET: Model
        public ActionResult Index()
        {
            ViewBag.Icon = "fa-search";
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }
    }
}

Frontend/Views/ShippingInstruction/Index.cshtml
@{
    ViewBag.Title = "Search Shipping Instruction";
    ViewBag.Module = "Shipping Instruction";
}

<div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-darken" id="wid-id-search-filter" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
            <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>Search Filters</h2>
            </header>

            <div>
                <div class="widget-body">
                    <div class="smart-form">
                        <fieldset>
                            <div class="row">
                                <section class="col col-2">
                                    <label class="label">Client Code</label>
                                    <label class="input">
                                        <input class="search-filter" type="text" ng-model="filters.ClientUD" />
                                    </label>
                                </section>
                                <section class="col col-2">
                                    <label class="label">POD</label>
                                    <label class="select">
                                        <select class="form-control search-filter" ng-model="filters.PODID" ng-options="poD.podid as poD.podName for poD in poDs">
                                            <option value=""></option>
                                        </select>
                                        <i></i>
                                    </label>
                                </section>
                                <section class="col col-2">
                                    <label class="label">P/I No</label>
                                    <label class="input">
                                        <input class="search-filter" type="text" ng-model="filters.ProformaInvoiceNo" />
                                    </label>
                                </section>  
                                <section class="col col-2">
                                    <label class="label">Priority</label>
                                    <label class="select">
                                        <select class="form-control search-filter" ng-model="filters.Priority">
                                            <option value=""></option>
                                            <option value="H">HIGH</option>
                                            <option value="M">MEDIUM</option>
                                            <option value="L">LOW</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </section> 
                                <section class="col col-2">
                                    <label class="label">Default</label>
                                    <label class="select">
                                        <select class="form-control search-filter" ng-model="filters.IsDefault">
                                            <option value=""></option>
                                            <option value="1">Yes</option>
                                            <option value="0">No</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </section>         
                                <section class="col col-2">
                                    <label class="label">Sparepart/Sample</label>
                                    <label class="select">
                                        <select class="form-control search-filter" ng-model="filters.IsSample">
                                            <option value=""></option>
                                            <option value="1">Yes</option>
                                            <option value="0">No</option>
                                        </select>
                                        <i></i>
                                    </label>
                                </section>                            
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>

        <div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
            <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>Search Result</h2>
            </header>

            <div>
                <div class="widget-body">
                    <div id="grdSearchResult" class="tilsoft-table-wrapper">
                        <div class="tilsoft-table">
                            <div class="tilsoft-table-header" style="width: 2120px;">
                                <div style="width: 60px;"></div>
                                <div style="width: 90px;">Confirmed</div>
                                <div style="width: 100px;">Sparepart / sample</div>
                                <div style="width: 90px;">Default</div>
                                <div style="width: 90px;">LC</div>
                                <div style="width: 90px;">Telex</div>
                                <div style="width: 90px;" class="sorting" data-colname="Priority">Priority</div>
                                <div style="width: 90px;" class="sorting" data-colname="ProformaInvoiceNo">P/I</div>
                                <div style="width: 90px;" class="sorting" data-colname="ClientUD">Client</div>
                                <div style="width: 150px;" class="sorting" data-colname="ForwarderNM">Forwarder</div>
                                <div style="width: 150px;" class="sorting" data-colname="PODName">POD</div>
                                <div style="width: 150px;">Notify Type</div>
                                <div style="width: 150px;">Notify Info</div>
                                <div style="width: 150px;">Consignee Type</div>
                                <div style="width: 150px;">Consignee Info</div>
                                <div style="width: 100px;" class="sorting" data-colname="UpdatorName">Updated By</div>
                                <div style="width: 100px;" class="sorting_desc" data-colname="UpdatedDate">Updated Date</div>
                                <div style="width: 100px;" class="sorting" data-colname="ConfirmerName">Confirmed By</div>
                                <div class="sorting" data-colname="ConfirmedDate">Confirmed<br /> Date</div>
                            </div>
                            <div class="tilsoft-table-body" style="width: 2120px;">
                                <table>
                                    <tr ng-repeat="model in data">
                                        <td style="text-align: center; width: 59px;">
                                            @if (Frontend.Helper.AuthHelper.GetActionButtonStatus(ViewBag.ModuleCode, Frontend.Helper.ActionEnum.Update, HttpContext.Current) == "disabled")
                                            {
                                                <a class="btn btn-primary btn-xs font-11" href="@Url.Action("Edit", "ShippingInstruction")/{{model.shippingInstructionID}}" title="View (Read Only)"><i class="fa fa-folder-open"></i> View</a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-primary btn-xs font-11" href="@Url.Action("Edit", "ShippingInstruction")/{{model.shippingInstructionID}}" title="Edit"><i class="fa fa-pencil"></i> Edit</a>
                                            }
                                        </td>
                                        <td style="text-align: center; width: 90px;"><input type="checkbox" ng-model="model.isConfirmed" disabled /></td>
                                        <td style="text-align: center; width: 100px;"><input type="checkbox" ng-model="model.isSample" disabled /></td>
                                        <td style="text-align: center; width: 90px;"><input type="checkbox" ng-model="model.isDefault" disabled /></td>
                                        <td style="text-align: center; width: 90px;"><input type="checkbox" ng-model="model.islc" disabled /></td>
                                        <td style="text-align: center; width: 90px;"><input type="checkbox" ng-model="model.isTelex" disabled /></td>
                                        <td style="width: 90px;">{{model.priority}}</td>
                                        <td style="width: 90px;">{{model.proformaInvoiceNo}}</td>
                                        <td style="width: 90px;">{{model.clientUD}}</td>
                                        <td style="width: 150px;">{{model.forwarderNM}}</td>
                                        <td style="width: 150px;">{{model.podName}}</td>
                                        <td style="width: 150px;">{{model.notifyTypeNM}}</td>
                                        <td style="width: 150px;">{{model.notifyInfo}}</td>
                                        <td style="width: 150px;">{{model.consigneeTypeNM}}</td>
                                        <td style="width: 150px;">{{model.consigneeInfo}}</td>
                                        <td style="width: 100px;">{{model.updatorName}}</td>
                                        <td style="width: 100px;">{{model.updatedDate}}</td>
                                        <td style="width: 100px;">{{model.confirmerName}}</td>
                                        <td>{{model.confirmedDate}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </article>
</div>

@section FormAction {
    <ul id="sparks">
        <li class="sparks-info">
            <a href="javascript:void(0);" class="btn btn-default" title="Search" ng-click="event.reload()"><i class="fa fa-search"></i></a>
        </li>
        <li class="sparks-info">
            <a href="javascript:void(0);" class="btn btn-default" title="Refresh" ng-click="event.reload()"><i class="fa fa-refresh"></i></a>
        </li>
        <li class="sparks-info">
            <a href="javascript:void(0)" class="btn btn-default disabled" title="New"><i class="fa fa-file-o"></i></a>
        </li>
        <li class="sparks-info">
            <a href="javascript:void(0);" class="btn btn-default " title="Print" ng-click="event.exportExcel()"><i class="fa fa-print"></i></a>
        </li>
    </ul>
}

@section pagejs {
    <script src="~/Angular/app/jsonService.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
    <script type="text/javascript">
        jsonService.serviceUrl = '@(System.Configuration.ConfigurationManager.AppSettings["BackendServiceUrl"])api/shippinginstruction/';
        jsonService.token = '@Session[Frontend.Customize.Common.ProjectDefinition.TOKEN_SESSION]';
        jsonService.searchFilter.pageSize = @System.Configuration.ConfigurationManager.AppSettings["DefaultPageSize"];
        jsonService.backendReportUrl = '@System.Configuration.ConfigurationManager.AppSettings["BackendReportUrl"]';
        var context = {
            editUrl: '@Url.Action("Edit", "ShippingInstruction")'
        }
    </script>
    <script src="~/Angular/app/shippingInstruction/service.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
    <script src="~/Angular/app/shippingInstruction/index.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
}