Frontend/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private string moduleCode = "ClientMng";

        // GET: Model
        public ActionResult Index()
        {
            ViewBag.Icon = "fa-search";
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult Overview(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

    }
}

Frontend/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class ModelController : Controller
    {
        private string moduleCode = "ModelMng";

        // GET: Model
        public ActionResult Index()
        {
            ViewBag.Icon = "fa-search";
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult View(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult SampleProduct(int id, int sampleProductID)
        {
            ViewBag.Icon = "fa-file-o";
            ViewBag.ID = id;
            ViewBag.SampleProductID = sampleProductID;
            ViewBag.ModuleCode = moduleCode;

            return View();
        }
    }
}

Frontend/Controllers/OfferSeasonMngController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
	[Authorize]
    public class OfferSeasonMngController : Controller
    {
        private string ModuleCode = "OfferSeasonMng";
        public ActionResult Index()
        {
            ViewBag.Icon = "fa-search";
            ViewBag.ModuleCode = ModuleCode;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ModuleCode = ModuleCode;
            ViewBag.ID = id;
            return View();
        }

        public ActionResult _InitForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_InitForm.cshtml");
        }        

        public ActionResult _EditFobProductForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_EditFobProductForm.cshtml");
        }

        public ActionResult _EditFobSparepartForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_EditFobSparepartForm.cshtml");
        }

        public ActionResult _EditWarehouseForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_EditWarehouseForm.cshtml");
        }

        public ActionResult _SearchModelForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_SearchModelForm.cshtml");
        }

        public ActionResult _SearchProductForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_SearchProductForm.cshtml");
        }

        public ActionResult _SearchSparepartForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_SearchSparepartForm.cshtml");
        }

        public ActionResult _OfferItemProperiesForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_OfferItemProperiesForm.cshtml");
        }

        public ActionResult _OfferSparepartProperiesForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_OfferSparepartProperiesForm.cshtml");
        }
        public ActionResult _PlanningPurchasingPriceForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_PlanningPurchasingPriceForm.cshtml");
        }

        public ActionResult _EditFobSampleForm()
        {
            ViewBag.ModuleCode = ModuleCode;
            return PartialView("~/Views/OfferSeasonMng/_Edit/_EditFobSampleForm.cshtml");
        }
    }
}

Frontend/Views/OfferSeasonMng/_Edit/_InitForm.cshtml
<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget" id="wid-id-general" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
        <header>
            <span class="widget-icon">
                <i class="fa fa-database"></i>
            </span>
            <h2>Select type of offer</h2>
        </header>
        <div>
            <div class="widget-body">
                <div class="smart-form">
                    <section>
                        <div class="inline-group">
                            <label class="radio" ng-repeat="item in offerSeasonTypeDTOs | orderBy : 'displayOrder'">
                                <input type="radio" name="radio-inline" ng-model="param.selectedOfferSeasonTypeID" ng-value="item.offerSeasonTypeID">
                                <i></i>{{item.offerSeasonTypeNM}}
                            </label>
                        </div>
                    </section>
                </div>
                <div>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Index", "OfferSeasonMng")"><i class="fa fa-times"></i> Cancel</a>
                    <a href="@Url.Action("Edit", "OfferSeasonMng")/0?typeID=1#/edit-warehouse-form" ng-if="param.selectedOfferSeasonTypeID==1" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Next</a>
                    <a href="@Url.Action("Edit", "OfferSeasonMng")/0?typeID=2#/edit-fob-product-form" ng-if="param.selectedOfferSeasonTypeID==2" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Next</a>
                    <a href="@Url.Action("Edit", "OfferSeasonMng")/0?typeID=3#/edit-fob-product-form" ng-if="param.selectedOfferSeasonTypeID==3" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Next</a>
                    <a href="@Url.Action("Edit", "OfferSeasonMng")/0?typeID=4#/edit-fob-sparepart-form" ng-if="param.selectedOfferSeasonTypeID==4" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Next</a>
                    <a href="@Url.Action("Edit", "OfferSeasonMng")/0?typeID=5#/edit-fob-sparepart-form" ng-if="param.selectedOfferSeasonTypeID==5" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Next</a>                    
                </div>
            </div>
        </div>
    </div>
</article>

Frontend/Views/OfferSeasonMng/_Edit/_OfferSparepartProperiesForm.cshtml
<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget" id="wid-id-general" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
        <header>
            <span class="widget-icon">
                <i class="fa fa-refresh"></i>
            </span>
            <h2>Sparepart property</h2>
        </header>
        <div>
            <div class="widget-body-toolbar">
                <a class="btn btn-warning btn-sm" href="#/edit-fob-sparepart-form"><i class="fa fa-arrow-left"></i> Back</a>
                <a class="btn btn-success btn-sm" href="#/edit-fob-sparepart-form"><i class="fa fa-check"></i> OK</a>
            </div>
            <div class="widget-body">
                <div class="smart-form">
                    <div class="row">
                        <section class="col col-lg-12">
                            <div>
                                <div class="full-panel">
                                    <h4>General</h4>
                                    <div class="filter-list-container" style="min-height: 0px;">
                                        <span class="form-control"><b>ARTICLECODE: </b>{{offerDetailItem.articleCode}}</span>
                                        <br />
                                        <span class="form-control"><b>DESCRIPTION: </b>{{offerDetailItem.description}}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="furnindo-filter">
                                <div class="filter-row">
                                    <div class="filter-panel">
                                        <h4>PART DESCRIPTION</h4>
                                        <div class="filter-list-container">
                                            <ul>
                                                <li>
                                                    <select class="form-control" name="partID" ng-model="offerDetailItem.partID" ng-options="sItem.modelSparepartID as sItem.description for sItem in modelSpareparts" ng-change="changeModelSparepart(offerDetailItem.partID)">
                                                        <option value=""></option>
                                                    </select>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>                            
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

Frontend/Views/OfferSeasonMng/_Edit/_PlanningPurchasingPriceForm.cshtml
<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="jarviswidget" id="wid-id-general" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
        <header>
            <span class="widget-icon">
                <i class="fa fa-refresh"></i>
            </span>
            <h2>Purchasing Price</h2>
        </header>
        <div>
            <div class="widget-body-toolbar">
                <a class="btn btn-warning btn-sm" href="{{getRouterWithParam(originRouter)}}"><i class="fa fa-arrow-left"></i> Back</a>                
                <a title="Client info" href="@Url.Action("Overview", "Client")/{{data.offerSeasonDTO.clientID}}" target="_blank">{{data.offerSeasonDTO.clientUD}}-{{data.offerSeasonDTO.clientNM}}</a>
            </div>
            <div class="widget-body">
                <div class="smart-form">
                    <a title="ArticleCode" href="@Url.Action("Edit", "Product")/{{offerDetailItemCopy.offerProductID}}" target="_blank"><span style="font-weight:bold;">{{offerDetailItemCopy.articleCode}}</span></a>
                    <br />
                    <a title="Description" href="@Url.Action("Edit", "Model")/{{offerDetailItemCopy.modelID}}" target="_blank">{{offerDetailItemCopy.description}}</a>
                    <div class="row">
                        <section class="col col-lg-12">
                            <table class="table table-bordered table-striped" style="box-sizing: border-box;">
                                <thead>
                                    <tr>
                                        <th style="width: 50px;"></th>
                                        <th style="width: 100px;">Factory</th>
                                        <th style="width: 100px;">Price</th>
                                        <th></th>
                                        <th style="width: 150px;"></th>
                                    </tr>
                                </thead>
                                <tbody ng-repeat="category in data.planingPurchasingPriceSourceDTOs">
                                    <tr>
                                        <td colspan="5">
                                            {{category.planingPurchasingPriceSourceNM}}
                                        </td>
                                    </tr>
                                    <tr ng-repeat="item in planningPurchasingPriceDTOs | filter: {planingPurchasingPriceSourceID : category.planingPurchasingPriceSourceID}" ng-if="item.planingPurchasingPriceSourceID !== 3">
                                        <td style="text-align: center;">
                                            <a ng-if="offerDetailItem.itemStatus !== 5" href="{{getRouterWithParam(originRouter)}}" class="btn btn-primary btn-xs" ng-click="selectPlaningPurchasingPrice(item)">Select</a>                                            
                                        </td>
                                        <td style="text-align: center;">{{item.factoryUD}}</td>
                                        <td style="text-align: right;">
                                            <a target="_blank" href="@Url.Action("Index", "EurofarPurchasingPriceMng")?articleCode={{offerDetailItem.articleCode}}&season={{$parent.data.offerSeasonDTO.season}}&type=5" ng-if="category.planingPurchasingPriceSourceID === 1">{{item.purchasingPrice | currency:'$':2}}</a>
                                            <font ng-if="category.planingPurchasingPriceSourceID !== 1">{{item.purchasingPrice | currency:'$':2}}</font>
                                        </td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    <tr ng-if="category.planingPurchasingPriceSourceID === 3">
                                        <td style="text-align: center;">
                                            @*has remark*@
                                            <a ng-if="offerDetailItemCopy.planingPurchasingPriceRemark && offerDetailItemCopy.itemStatus !== 5" href="{{getRouterWithParam(originRouter)}}" class="btn btn-warning btn-xs {{offerDetailItemCopy.estimatedPurchasingPrice && offerDetailItemCopy.estimatedPurchasingPriceFromFactoryID ? '' : 'disabled'}}" ng-click="selectPlaningPurchasingPrice(null)">Select</a>                                            

                                            @*has no remark*@
                                            <a ng-if="!offerDetailItemCopy.planingPurchasingPriceRemark && offerDetailItemCopy.itemStatus !== 5" href="javascript:void(0)" class="btn btn-warning btn-xs {{offerDetailItemCopy.estimatedPurchasingPrice && offerDetailItemCopy.estimatedPurchasingPriceFromFactoryID ? '' : 'disabled'}}" ng-click="selectPlaningPurchasingPrice(null)">Select</a>                                            
                                        </td>
                                        <td style="text-align: center;">
                                            <select ng-disabled="offerDetailItem.itemStatus === 5" style="padding: 3px;" ng-options="factory.factoryID as factory.factoryUD for factory in data.factoryDTOs" ng-model="offerDetailItemCopy.estimatedPurchasingPriceFromFactoryID">
                                                <option></option>
                                            </select>
                                        </td>
                                        <td style="text-align: left;">
                                            <input ng-disabled="offerDetailItem.itemStatus === 5" type="text" avs-currency-2 ng-model="offerDetailItemCopy.estimatedPurchasingPrice" style="padding: 2px; text-align: right;width: 100%" />
                                            <a ng-if="offerDetailItemCopy.estimatedPurchasingPriceUpdatedByID" href="@Url.Action("Detail", "EmployeeMng", new { id = UrlParameter.Optional })/{{offerDetailItemCopy.estimatedPurchasingPriceUpdatedByID}}" data-featherlight="iframe" data-featherlight-iframe-allowfullscreen="true" data-featherlight-iframe-width="800" data-featherlight-iframe-height="600">
                                                Updated by {{offerDetailItemCopy.estimatedPurchasingPriceUpdatedByName}} 
                                                <br />
                                                at {{offerDetailItemCopy.estimatedPurchasingPriceUpdatedDate}}
                                            </a>
                                        </td>
                                        <td>
                                            <textarea rows="13" placeholder="Please write your explanation as clear as possible"
                                                      ng-disabled="offerDetailItem.itemStatus === 5"
                                                      type="text"
                                                      ng-model="offerDetailItemCopy.planingPurchasingPriceRemark"
                                                      style="padding: 2px; width:100%; height:100%" />
                                            
                                            <div>
                                                Attach File:
                                                <a href="{{offerDetailItemCopy.planingPurchasingPriceFileLocation}}" target="_blank">{{offerDetailItemCopy.planingPurchasingPriceFileFriendlyName}}</a>
                                                <a ng-disabled="!offerDetailItemCopy.planingPurchasingPriceFileLocation" href="javascript:void(0);" class="btn btn-primary btn-xs" style="font-size: 11px;" ng-click="downloadFile()">Download</a>
                                                <a href="javascript:void(0);" class="btn btn-primary btn-xs" style="font-size: 11px;" ng-click="changeFile()">Change</a>
                                                <a ng-disabled="!offerDetailItemCopy.planingPurchasingPriceFileLocation" href="javascript:void(0);" class="btn btn-danger btn-xs" style="font-size: 11px;" ng-click="removeFile()">Remove</a>
                                            </div>
                                        </td>
                                        <td>
                                            <strong>Pending factory price</strong>
                                            <br />
                                            <span ng-repeat="price in factoryPendingPriceDTOs">
                                                <a ng-if="offerDetailItem.itemStatus !== 5" ng-click="selectPendingFactoryPrice(price)" href="{{getRouterWithParam(originRouter)}}" class="btn btn-success btn-xs" style="margin-bottom:5px; margin-right:10px">Select</a>                                                
                                                <font style="width: 100px; text-align: left; display: inline-block;">{{price.factoryUD}}</font>: <font style="width: 70px; text-align: right; display: inline-block;">{{price.salePrice | currency:'$':2}}</font>
                                                <br />
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" ng-if="(planningPurchasingPriceDTOs | filter: {planingPurchasingPriceSourceID : category.planingPurchasingPriceSourceID}).length === 0 && category.planingPurchasingPriceSourceID !== 3" style="text-align: center;">
                                            N/A
                                        </td>
                                    </tr>
                                </tbody>
                            </table>


                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

Frontend/Views/OfferSeasonMng/_Edit/_SearchModelForm.cshtml
<div id="model-popup" ng-show="isShowSearchModel">
    <div style="float: right; margin-bottom: 8px;">
        <a ng-click="event.cancel()" class="btn btn-danger btn-xs" href="javascript:void(0);"><i class="fa fa-remove"></i> Close</a>
        <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===2 || data.offerSeasonDTO.offerSeasonTypeID===3" ng-click="event.okFobProduct()" class="btn btn-primary btn-xs" href="#/offer-item-properties-form/edit-fob-product-form/{{offerSeasonDetailID}}"><i class="fa fa-check"></i> OK</a>
        <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===4 || data.offerSeasonDTO.offerSeasonTypeID===5" ng-click="event.okFobSparepart()" class="btn btn-primary btn-xs" href="#/offer-sparepart-properties-form/{{offerSeasonDetailID}}"><i class="fa fa-check"></i> OK</a>
        <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===6 || data.offerSeasonDTO.offerSeasonTypeID===7" ng-click="event.okFobProduct()" class="btn btn-primary btn-xs" href="#/offer-item-properties-form/edit-fob-sample-form/{{offerSeasonDetailID}}"><i class="fa fa-check"></i> OK</a>
    </div>
    <div class="clear"></div>
    <div class="tilsoft-table-wrapper" avs-scroll grid-handler="gridHandler">
        <div class="tilsoft-table">
            <div class="tilsoft-table-header" style="width: 1250px;">
                <div style="width: 70px;"></div>
                <div style="width: 50px;"></div>
                <div style="width: 60px;" class="sorting" data-colname="ModelUD">Model Code</div>
                <div style="width: 600px;" class="sorting" data-colname="ModelNM">Model Name</div>
                <div style="width: 70px;" class="sorting_desc" data-colname="Season">Season</div>
                <div style="width: 100px;" class="sorting" data-colname="RangeName">Range Name</div>
                <div style="width: 100px;" class="sorting" data-colname="Collection">Collection</div>
                <div style="width: 50px;" class="sorting" data-colname="Collection">Cata log Page</div>
                <div style="width: 130px;" class="sorting" data-colname="Collection">Status</div>
                <div></div>
            </div>
            <div class="tilsoft-table-body" style="width: 1250px; margin-top: 75px;">
                <table>
                    <tbody ng-repeat="item in searchResult">
                        <tr>
                            <td style="width:69px; text-align:left; vertical-align:middle">
                                <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===2 || data.offerSeasonDTO.offerSeasonTypeID===3" ng-click="event.selectedModelForFobProductForm(item)" href="#/offer-item-properties-form/edit-fob-product-form/{{offerSeasonDetailID}}" class="btn btn-primary btn-xs"><i class="fa fa-check"></i> Select</a>
                                <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===4 || data.offerSeasonDTO.offerSeasonTypeID===5" ng-click="event.selectedModelForFobSparepartForm(item)" href="#/offer-sparepart-properties-form/{{offerSeasonDetailID}}" class="btn btn-primary btn-xs"><i class="fa fa-check"></i> Select</a>
                                <a ng-if="data.offerSeasonDTO.offerSeasonTypeID===6 || data.offerSeasonDTO.offerSeasonTypeID===7" ng-click="event.selectedModelForFobProductForm(item)" href="#/offer-item-properties-form/edit-fob-sample-form/{{offerSeasonDetailID}}" class="btn btn-primary btn-xs"><i class="fa fa-check"></i> Select</a>
                            </td>
                            <td style="width:50px;text-align:left;">
                                <label class="checkbox">
                                    <input type="checkbox" ng-model="item.isSelected">
                                    <i style="top:0px; margin-left:10px"></i>
                                </label>
                            </td>
                            <td style="text-align: center; width: 60px">
                                <a ng-if="item.modelStatusID===1" style="color:#178b15" href="@Url.Action("Edit", "Model")/{{item.modelID}}" target="_blank">{{item.modelUD | uppercase}}</a>
                                <a ng-if="item.modelStatusID!==1" style="color:black" href="@Url.Action("Edit", "Model")/{{item.modelID}}" target="_blank">{{item.modelUD | uppercase}}</a>
                            </td>
                            <td style="text-align: left; width: 600px">
                                <a ng-if="item.modelStatusID===1" style="color:#178b15" href="@Url.Action("Edit", "Model")/{{item.modelID}}" target="_blank">{{item.modelNM | uppercase}}</a>
                                <a ng-if="item.modelStatusID!==1" style="color:black" href="@Url.Action("Edit", "Model")/{{item.modelID}}" target="_blank">{{item.modelNM | uppercase}}</a>
                            </td>
                            <td style="text-align: center; width: 70px">{{item.season | uppercase}}</td>
                            <td style="text-align: left; width: 100px">{{item.rangeName | uppercase}}</td>
                            <td style="text-align: left; width: 100px">{{item.collection | uppercase}}</td>
                            <td style="text-align: center; width: 50px">
                                <div ng-if="item.cataloguePageNo!==1000">{{item.cataloguePageNo | uppercase}}</div>
                            </td>
                            <td style="text-align: left; width: 130px">{{item.modelStatusNM | uppercase}}</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    
    </div>
</div>