Frontend/Controllers/FactoryFinishedProductReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Frontend.Controllers
{
    [Authorize]
    public class FactoryFinishedProductReceiptController : Controller
    {
        private string moduleCode = "FactoryFinishedProductReceiptMng";

        //GET: Model
        public ActionResult Index()
        {
            ViewBag.Icon = "fa-search";
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Icon = "fa-pencil-square-o";
            ViewBag.ID = id;
            ViewBag.ModuleCode = moduleCode;
            return View();
        }

        
    }
}

Frontend/Views/FactoryFinishedProductReceipt/Index.cshtml
@{
    ViewBag.Title = "Component Receipt";
    ViewBag.Module = "Component Receipt";
}
<div class="row">
    <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="jarviswidget jarviswidget-color-darken" id="wid-id-search-filter" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
            <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>Search Filters</h2>
            </header>

            <div>
                <div class="widget-body">
                    <div class="row">
                        <div class="col-sm-2 m-bottom-15">
                            <label>Receipt No</label>
                            <input class="form-control search-filter" type="text" ng-model="filters.receiptNo">
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="jarviswidget jarviswidget-color-darken" id="wid-id-search-result" data-widget-editbutton="false" data-widget-colorbutton="false" data-widget-fullscreenbutton="false" data-widget-deletebutton="false">
            <header>
                <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                <h2>Search Result</h2>
            </header>

            <div>
                <div class="jarviswidget-editbox"></div>

                <div class="widget-body">
                    <div class="table-responsive">
                        <div id="grdSearchResult" class="tilsoft-table-wrapper">
                            <div class="tilsoft-table">
                                <div class="tilsoft-table-header" style="width: 1500px;">
                                    <div style="width: 100px;"></div>
                                    <div style="width: 80px;" class="sorting" data-colname="ReceiptNo">Receipt No</div>
                                    <div style="width: 60px;" class="sorting" data-colname="ReceiptTypeText">Type</div>
                                    <div style="width: 150px;" class="sorting" data-colname="ImportFromTeamNM">Import From Team</div>
                                    <div style="width: 150px;" class="sorting" data-colname="ExportToTeamNM">Export To Team</div>
                                    <div style="width: 110px;" class="sorting" data-colname="FactoryStepNM">Step</div>
                                    <div style="width: 80px;" class="sorting" data-colname="Season">Season</div>
                                    <div style="width: 80px;" class="sorting" data-colname="ReceiptDate">Receipt Date</div>
                                    
                                    <div style="width: 150px;" class="sorting" data-colname="CreatorName">Created By</div>
                                    <div style="width: 80px;" class="sorting" data-colname="CreatedDate">Created Date</div>
                                    <div style="width: 150px;" class="sorting" data-colname="CreatedDate">Updated By</div>
                                    <div style="width: 80px;" class="sorting" data-colname="CreatedDate">UpdatedDate</div>
                                    <div class="sorting" data-colname="Remark">Remark</div>
                                </div>
                                <div class="tilsoft-table-body" style="width: 1500px;">
                                    <table>
                                        <tr ng-repeat="item in data">
                                            <td style="text-align: center; width: 99px;">
                                                @if (Frontend.Helper.AuthHelper.GetActionButtonStatus(ViewBag.ModuleCode, Frontend.Helper.ActionEnum.Update, HttpContext.Current) == "disabled")
                                                {
                                                    <a class="btn btn-primary btn-xs font-11" href="@Url.Action("Edit", "factoryFinishedProductReceipt")/{{item.factoryFinishedProductReceiptID}}" title="View (Read Only) title=" view (read only)" target="_blank"><i class="fa fa-folder-open"></i>View</a>
                                                }
                                                else
                                                {
                                                    <a class="btn btn-primary btn-xs font-11" href="@Url.Action("Edit", "factoryFinishedProductReceipt")/{{item.factoryFinishedProductReceiptID}}" title="Edit" target="_blank"><i class="fa fa-pencil"></i>Edit</a>
                                                }

                                                @if (Frontend.Helper.AuthHelper.GetActionButtonStatus(ViewBag.ModuleCode, Frontend.Helper.ActionEnum.Delete, HttpContext.Current) != "disabled")
                                                {
                                                    <a class="btn btn-danger btn-xs font-11" href="#" ng-click="event.delete(item.factoryFinishedProductReceiptID,$event)" title="Delete"><i class="fa fa-times"></i>Del</a>
                                                }
                                            </td>
                                            <td style="width: 80px;">{{item.receiptNo}}</td>
                                            <td style="width: 60px;">{{item.receiptTypeText}}</td>
                                            <td style="width: 150px;">{{item.importFromTeamNM}}</td>
                                            <td style="width: 150px;">{{item.exportToTeamNM}}</td>
                                            <td style="width: 110px;">{{item.factoryStepNM}}</td>
                                            <td style="width: 80px;">{{item.season}}</td>
                                            <td style="width: 80px;">{{item.receiptDate}}</td>
                                            
                                            <td style="width: 150px;">
                                                <avs-show-dialog-link is-show="item.showCreatorLink"
                                                                      navigate-url="'@Url.Action("Detail", "EmployeeMng", new { id = UrlParameter.Optional })/' + item.creatorID"
                                                                      display-text="item.creatorName"></avs-show-dialog-link>
                                            </td>
                                            <td style="width: 80px;">{{item.createdDate}}</td>
                                            <td style="width: 150px;">
                                                <avs-show-dialog-link is-show="item.showUpdatorLink"
                                                                      navigate-url="'@Url.Action("Detail", "EmployeeMng", new { id = UrlParameter.Optional })/' + item.updatorID"
                                                                      display-text="item.updatorName"></avs-show-dialog-link>
                                            </td>
                                            <td style="width: 80px;">{{item.updatedDate}}</td>
                                            <td>{{item.remark}}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
</div>

@section FormAction {
    <ul id="sparks">
        <li class="sparks-info">
            <a href="javascript:void(0);" class="btn btn-default" title="Search" ng-click="event.reload()"><i class="fa fa-search"></i></a>
        </li>
        <li class="sparks-info">
            <a href="javascript:void(0);" class="btn btn-default" title="Refresh" ng-click="event.reload()"><i class="fa fa-refresh"></i></a>
        </li>
        <li class="sparks-info">
            <a href="@Url.Action("Edit", "FactoryFinishedProductReceipt")/0" class="btn btn-default @(Frontend.Helper.AuthHelper.GetActionButtonStatus(ViewBag.ModuleCode, Frontend.Helper.ActionEnum.Create, HttpContext.Current))" title="New" target="_blank"><i class="fa fa-file-o"></i></a>
        </li>
    </ul>
}

@section pagejs {
    <script src="~/Angular/app/jsonService.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
    <script src="~/Angular/app/support/service.js?c=@System.Guid.NewGuid().ToString().Replace("-","")"></script>
    <script type="text/javascript">
        jsonService.serviceUrl = '@(System.Configuration.ConfigurationManager.AppSettings["BackendServiceUrl"])api/factoryFinishedProductReceipt/';
        jsonService.token = '@Session[Frontend.Customize.Common.ProjectDefinition.TOKEN_SESSION]';

        supportService.serviceUrl = '@(System.Configuration.ConfigurationManager.AppSettings["BackendServiceUrl"])api/support/';
        supportService.token = '@Session[Frontend.Customize.Common.ProjectDefinition.TOKEN_SESSION]';

        jsonService.searchFilter.pageSize = '@System.Configuration.ConfigurationManager.AppSettings["DefaultPageSize"]';
    var context = {
        editUrl: '@Url.Action("Edit", "FactoryFinishedProductReceipt")',
        reportUrl: '@System.Configuration.ConfigurationManager.AppSettings["BackendReportUrl"]'
    }
    </script>
    <script src="~/Angular/app/factoryFinishedProductReceipt/service.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
    <script src="~/Angular/app/factoryFinishedProductReceipt/index.js?c=@System.Guid.NewGuid().ToString().Replace("-", "")"></script>
}